# Generated by Django 5.0.1 on 2024-07-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('ph', models.CharField(max_length=15)),
                ('info', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
