# Generated by Django 5.0.1 on 2024-07-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_com', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ph',
            field=models.CharField(max_length=20),
        ),
    ]
