# Generated by Django 5.0.6 on 2024-07-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.IntegerField()),
                ('id_no', models.IntegerField()),
                ('dept', models.CharField(max_length=120)),
                ('salary', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
