# Generated by Django 5.0.6 on 2024-07-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_frist_name_employee_fristname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fristname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
